version: '3.3'
services:
  mysql:
    image: mysql:5
    # restart: always
    environment:
      - MYSQL_DATABASE=pragma_ruta_back
      # So you don't have to use root, but you can if you like
      # - MYSQL_USER=root
      # # You can use whatever password you like
      # - MYSQL_PASSWORD= 'password'
      # Password for root access
      - MYSQL_ROOT_PASSWORD=123456
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    # expose:
    #   # Opens port 3306 on the container
    #   - '3306'
    #   # Where our data will be persisted
    volumes:
      - ./db/mysql_data:/var/lib/mysql
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - PMA_HOST=mysql
      # - PMA_PORT=3366
    ports:
      - '8080:80'
    depends_on:
      - mysql
      - mongo

  mongo:
    image: mongo:4.4
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: pragma_ruta_back_mongo
    ports:
      - "27017:27017"
    volumes:
     - ./db/mongo_data:/data/db

  mongo_express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongo:27017/
    depends_on:
      - mongo
    
  # node:
  #   image: node:19
  #   ports: 
  #     - '3001:3001'
  #   depends_on:
  #     - mysql
  #     - mongo
  #     - phpmyadmin
  #     - mongo_express
  #   volumes:
  #     - ./prueba:/home/node/backend
  #   working_dir: ./
  #   command: npm run dev
